server:
  port: 8081
spring:
  application:
    name: tiktok-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tiktok?useSSL=True&serverTimezone=UTC
    username: root
    password: 2002
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）

dubbo:
  application:
    name: tiktok-user
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848