spring:
  application:
    name: tiktok-gateway
  cloud:
    gateway:
      routes:

        - id: tiktok-video
          uri: lb://tiktok-video # lb 代表负载均衡
          predicates:
            - Path=/video/**
        - id: tiktok-comment
          uri: lb://tiktok-comment
          predicates:
            - Path=/comment/**
        - id: tiktok-message
          uri: lb://tiktok-message
          predicates:
            - Path=/message/**
        - id: tiktok-relation
          uri: lb://tiktok-relation
          predicates:
            - Path=/relation/**,/favorite/**
        - id: tiktok-user
          uri: lb://tiktok-user
          predicates:
            - Path=/user/**
    nacos:
      discovery:
        server-addr: localhost:8848


server:
  port: 8099
